# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Files to Staging Directory'

- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)'
    MachineNames: 'DevOps-WinTest-vm'
    AdminUserName: 'deepak.sahoo'
    AdminPassword: 'Welcome$2024'
    TargetPath: 'C:\apps\IIS_dir\html'
  displayName: 'Copy Files to VM Virtual Directory'
